# Generated by Django 3.0.3 on 2020-06-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
