# Generated by Django 3.0.3 on 2020-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0005_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
