# Generated by Django 3.0.3 on 2020-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0006_auto_20200607_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(default='june 21 2020'),
            preserve_default=False,
        ),
    ]
