# Generated by Django 3.0.3 on 2020-06-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopp', '0011_orderitem_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_date',
        ),
    ]
